"use client";
import { useEffect, useRef, useState } from "react";
import { motion, useMotionValue, useSpring } from "framer-motion";
import { ArrowDown, ArrowUpRight, Download, Code2, ContactRound, Mail, Moon, Sun } from "lucide-react";
import { portfolio } from "./data";
const ease = [0.22, 1, 0.36, 1] as const;

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: .8, ease }}>{children}</motion.div> }
function Network() { return <div className="network" aria-hidden="true"><svg viewBox="0 0 900 640" preserveAspectRatio="xMidYMid slice"><g><path d="M30 440L180 260L345 350L510 160L690 270L870 90"/><path d="M180 260L250 80M345 350L450 520M510 160L690 270L790 500M30 440L270 560"/></g>{[[30,440],[180,260],[345,350],[510,160],[690,270],[870,90],[250,80],[450,520],[790,500],[270,560]].map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r={i%3===0?7:4}/>)}</svg></div> }
function MagneticLink({ href, children, secondary=false }: { href:string; children:React.ReactNode; secondary?:boolean }) { const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:180,damping:16}),sy=useSpring(y,{stiffness:180,damping:16}); return <motion.a href={href} className={secondary?"button secondary":"button"} style={{x:sx,y:sy}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.15);y.set((e.clientY-r.top-r.height/2)*.15)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.a> }
function Cursor() { const x=useMotionValue(-50),y=useMotionValue(-50),sx=useSpring(x,{stiffness:500,damping:35}),sy=useSpring(y,{stiffness:500,damping:35}); useEffect(()=>{const move=(e:MouseEvent)=>{x.set(e.clientX-12);y.set(e.clientY-12)};window.addEventListener("mousemove",move);return()=>window.removeEventListener("mousemove",move)},[x,y]); return <motion.div className="cursor" style={{x:sx,y:sy}} aria-hidden="true"/> }
function TiltCard({ children, className="" }: {children:React.ReactNode;className?:string}) { const ref=useRef<HTMLDivElement>(null),rx=useMotionValue(0),ry=useMotionValue(0); return <motion.div ref={ref} className={className} style={{rotateX:rx,rotateY:ry,transformPerspective:900}} onMouseMove={e=>{const r=ref.current!.getBoundingClientRect();ry.set(((e.clientX-r.left)/r.width-.5)*5);rx.set(-((e.clientY-r.top)/r.height-.5)*5)}} onMouseLeave={()=>{rx.set(0);ry.set(0)}}>{children}</motion.div> }
function Header({ theme, toggle }: {theme:string;toggle:()=>void}) { const [open,setOpen]=useState(false); return <header><a className="monogram" href="#top">AV<span>.</span></a><nav className={open?"open":""}>{["About","Experience","Projects","Skills","Contact"].map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setOpen(false)}>{x}</a>)}</nav><div className="nav-actions"><button className="theme" onClick={toggle} aria-label="Toggle color theme">{theme==="dark"?<Sun/>:<Moon/>}</button><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation"><span/><span/></button></div></header> }
function Hero() {
  const [role,setRole]=useState(0);
  useEffect(()=>{const id=setInterval(()=>setRole(r=>(r+1)%portfolio.roles.length),2400);return()=>clearInterval(id)},[]);
  return <section className="hero reference-hero" id="top">
    <Network/>
    <div className="hero-index">PORTFOLIO / 2026</div>
    <div className="hero-content">
      <motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.2}} className="eyebrow">Hi, I’m Anoop Vamsi Meduri</motion.p>
      <div className="reference-grid">
        <motion.div className="hero-role-copy" initial={{opacity:0,x:-45}} animate={{opacity:1,x:0}} transition={{duration:.9,ease}}>
          <span className="role-kicker">I design &amp; build</span>
          <motion.h1 key={role} initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.6,ease}}>
            {portfolio.roles[role].split(" ").map((word,i)=><span key={i}>{word}<br/></span>)}
          </motion.h1>
        </motion.div>
        <motion.div className="portrait-wrap portrait-stage" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{delay:.15,duration:1,ease}}>
          <div className="portrait-halo"/>
          <img src="/anoop-portrait.png" alt="Anoop Vamsi Meduri"/>
          <div className="availability"><i/> Open to AI/ML opportunities</div>
        </motion.div>
        <motion.div className="hero-summary" initial={{opacity:0,x:45}} animate={{opacity:1,x:0}} transition={{delay:.25,duration:.9,ease}}>
          <span>Turning data into decisions</span>
          <p>I build reliable Generative AI, machine-learning, and data systems for complex enterprise problems.</p>
          <div className="hero-ctas"><MagneticLink href="#projects">View my work <ArrowDown/></MagneticLink><MagneticLink href={portfolio.links.resume} secondary>Resume <Download/></MagneticLink></div>
        </motion.div>
      </div>
      <div className="reference-footer"><span>↓ Scroll to explore</span><div className="socials"><a href={portfolio.links.linkedin} aria-label="LinkedIn"><ContactRound/></a><a href={portfolio.links.github} aria-label="GitHub"><Code2/></a><a href="#contact" aria-label="Email"><Mail/></a></div></div>
    </div>
  </section>
}
function About(){return <section id="about" className="section about"><Reveal><p className="section-label">01 / About</p><div className="about-grid"><h2>Engineering AI<br/>with <em>evidence.</em></h2><div><p className="lead">I’m a Senior AI/ML Engineer with 7+ years of experience building data platforms, machine-learning solutions, and enterprise Generative AI applications.</p><p>My recent work focuses on RAG systems, AI agents, LLM evaluation, document intelligence, and production-grade AI applications across AWS, Azure, and GCP.</p></div></div></Reveal><div className="stats">{[["7+","Years of experience"],["04","Major industries"],["03","Cloud platforms"],["∞","End-to-end delivery"]].map(([v,l],i)=><Reveal key={l}><div className="stat"><span>0{i+1}</span><strong>{v}</strong><p>{l}</p></div></Reveal>)}</div></section>}
function Experience(){const [active,setActive]=useState(0);return <section id="experience" className="section experience"><Reveal><p className="section-label">02 / Experience</p><div className="section-head"><h2>Where I’ve<br/><em>made impact.</em></h2><p>A career spanning financial services, healthcare, mortgage technology, analytics, and enterprise data.</p></div></Reveal><div className="timeline">{portfolio.experiences.map((e,i)=><motion.button key={e.company} className={`experience-row ${active===i?"active":""}`} onClick={()=>setActive(i)} onMouseEnter={()=>setActive(i)} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} aria-expanded={active===i}><span className="timeline-dot"/><span className="exp-num">0{i+1}</span><span className="exp-company">{e.company}</span><span className="exp-role">{e.role}</span><span className="exp-period">{e.period}</span><ArrowUpRight/><motion.p className="exp-detail" animate={{height:active===i?"auto":0,opacity:active===i?1:0}}>{e.detail}</motion.p></motion.button>)}</div></section>}
function Projects(){const [open,setOpen]=useState(0);return <section id="projects" className="section projects"><Reveal><p className="section-label">03 / Selected work</p><div className="section-head"><h2>Systems built for<br/><em>the real world.</em></h2><p>Selected projects across retrieval, intelligent agents, secure enterprise AI, and evaluation.</p></div></Reveal><div className="project-track">{portfolio.projects.map((p,i)=><TiltCard key={p.title} className={`project-card p${i}`}><div className="project-top"><span>{p.kicker}</span><b>{p.number}</b></div><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="project-actions"><button onClick={()=>setOpen(open===i?-1:i)}>{open===i?"Close case study":"View case study"} <ArrowUpRight/></button>{p.github&&<a href={p.github}>View GitHub <Code2/></a>}</div><motion.div className="case-study" animate={{height:open===i?"auto":0,opacity:open===i?1:0}}>{Object.entries(p.details).map(([k,v])=><div key={k}><span>{k}</span><p>{v}</p></div>)}<div><span>Technology Stack</span><p>{p.stack.join(" · ")}</p></div></motion.div></TiltCard>)}</div></section>}
const pipeline=["Documents","Extraction","Chunking","Embeddings","Vector DB","Hybrid Retrieval","Reranking","LLM","Grounded Answer"];
function Architecture(){return <section className="section architecture"><Reveal><p className="section-label">04 / Architecture</p><div className="section-head"><h2>From document to<br/><em>grounded answer.</em></h2><p>A modern retrieval pipeline designed to make model output relevant, traceable, and useful.</p></div></Reveal><Reveal className="pipeline"><div className="flow-line"><motion.i initial={{left:"0%"}} whileInView={{left:"98%"}} viewport={{once:false}} transition={{duration:6,repeat:Infinity,ease:"linear"}}/></div>{pipeline.map((x,i)=><div className="node" key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</Reveal></section>}
function Skills(){return <section id="skills" className="section skills"><Reveal><p className="section-label">05 / Capabilities</p><div className="section-head"><h2>Deep expertise.<br/><em>Practical delivery.</em></h2><p>Tools are selected for the problem—not the trend.</p></div></Reveal><div className="skill-grid">{Object.entries(portfolio.skills).map(([group,items],i)=><Reveal key={group}><div className="skill-group"><span>0{i+1}</span><h3>{group}</h3><div>{items.map(x=><b key={x}>{x}</b>)}</div></div></Reveal>)}</div></section>}
function Contact(){return <section id="contact" className="contact"><Network/><Reveal><p className="section-label">06 / Contact</p><h2>Let’s build intelligent<br/>systems that work in<br/><em>the real world.</em></h2><div className="contact-links"><a href={portfolio.email?`mailto:${portfolio.email}`:"mailto:"}>Email me <ArrowUpRight/></a><a href={portfolio.links.linkedin}>Connect on LinkedIn <ArrowUpRight/></a><a href={portfolio.links.github}>View GitHub <ArrowUpRight/></a><a href={portfolio.links.resume}>Download resume <Download/></a></div></Reveal><footer><span>© 2026 Anoop Vamsi Meduri</span><span>AI / ML / DATA</span><a href="#top">Back to top ↑</a></footer></section>}
export default function Home(){const [theme,setTheme]=useState("dark");useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);return <main><Cursor/><Header theme={theme} toggle={()=>setTheme(t=>t==="dark"?"light":"dark")}/><Hero/><About/><Experience/><Projects/><Architecture/><Skills/><Contact/></main>}
